job_base: &job_base
  working_directory: ~/circleci-envclasses
  docker:
    - image: circleci/python:3.7.4
      environment:
        PIPENV_VENV_IN_PROJECT: true


version: 2.1
jobs:
  build:
    <<: *job_base
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install Pipenv and Dependencies
          command: |
            pip install pipenv
            pipenv install --dev
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
  test:
    <<: *job_base
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Lint The Source Code
          command: |
            mkdir -p test-results/pylint test-results/pytest
            pipenv run pylint -f text -r y envclasses &> test-results/pylint/pylint-report.txt
            pipenv run pytest --junitxml=test-results/pytest/junit.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: test-results

workflows:
  version: 2
  test:
    jobs:
      - build
      - test:
          requires:
            - build

