version: 2.1
jobs:
  lint:
    docker:
      - image: python:alpine
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pipenv install --dev
      - run:
          name: Lint Sourceo
          command: pipenv run pylint envclasses

workflows:
  version: 2
  test:
    - lint
